# Generated by Django 5.0.1 on 2024-01-25 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=220)),
                ("image", models.CharField(max_length=220)),
                (
                    "gread",
                    models.CharField(
                        choices=[("1", "1"), ("5", "5"), ("12", "12")], max_length=220
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("username", models.CharField(max_length=220, unique=True)),
                ("password", models.CharField(max_length=220)),
                ("age", models.IntegerField()),
                (
                    "gread",
                    models.CharField(
                        choices=[("1", "1"), ("5", "5"), ("12", "12")], max_length=220
                    ),
                ),
                ("points", models.IntegerField(default=0)),
                (
                    "videos_watched",
                    models.CharField(blank=True, default="", max_length=220),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=220)),
                ("quiz", models.CharField(max_length=220)),
                ("answer", models.CharField(max_length=220)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.course"
                    ),
                ),
            ],
        ),
    ]
